// GENERATED CODE - DO NOT EDIT
// Generated from CLAUDE.md fallback

u8 bootstrap_content_data[] =
  "# CLAUDE.md\n"
  "\n"
  "Guidance to Claude Code.\n"
  "\n"
  "\n"
  "## Overview\n"
  "\n"
  "cmpr provides code block database features.\n"
  "\n"
  "**cmpr1 vs cmpr2**: This is the cmpr1 codebase (C implementation). The parent directory contains cmpr2 (Python implementation), which is more feature-complete. To access cmpr2 blocks from cmpr1: `cd ../cmpr; cmpr --print-comment` followed by the block ID.\n"
  "\n"
  "**CLAUDE.md Principle**: This file teaches HOW to work with cmpr (commands, workflow, principles), not WHAT the codebase contains (structure, subsystems, features). Code navigability belongs in the navigable block structure itself. Almost no specific block IDs should appear in CLAUDE.md - navigation information lives in the code, accessed by reading the root block and following references.\n"
  "\n"
  "## Building and Testing\n"
  "\n"
  "```bash\n"
  "# Production build\n"
  "make\n"
  "\n"
  "# Install\n"
  "sudo make install\n"
  "\n"
  "# Run the installed binary\n"
  "cmpr\n"
  "\n"
  "# Run the build that `make` generates without installing it\n"
  "dist/cmpr\n"
  "```\n"
  "\n"
  "The cmpr --help output and build system details are documented in blocks accessible from the root block.\n"
  "\n"
  "## Code Updates\n"
  "\n"
  "**MANDATORY FIRST STEP FOR EVERY TASK**:\n"
  "\n"
  "When the user asks you to work on ANY task related to this codebase, you MUST:\n"
  "\n"
  "1. **START by reading the root block**: `cmpr --print-comment` with the root block ID\n"
  "2. **NAVIGATE using block references**: Follow block IDs mentioned in the output (2-3 hops to reach any part of codebase)\n"
  "3. **NEVER use the Task tool with Explore subagent** - it uses traditional tools and defeats the entire cmpr workflow\n"
  "4. **NEVER start with grep/find/Read/Glob** - these are fallbacks for when cmpr navigation fails\n"
  "\n"
  "**Example of CORRECT workflow**:\n"
  "```\n"
  "User: \"I want to work on the agent system\"\n"
  "Assistant: [Immediately runs] cmpr --print-comment on the root block\n"
  "Assistant: [Sees reference to agent hub, follows it] cmpr --print-comment on that hub\n"
  "Assistant: [Now understands the structure and can navigate to specific blocks]\n"
  "```\n"
  "\n"
  "**Example of WRONG workflow**:\n"
  "```\n"
  "User: \"I want to work on the agent system\"\n"
  "Assistant: [Uses Task tool with Explore subagent] ❌ WRONG\n"
  "Assistant: [Uses grep to search for \"agent\"] ❌ WRONG\n"
  "Assistant: [Uses Glob to find agent files] ❌ WRONG\n"
  "```\n"
  "\n"
  "**Always prefer cmpr commands over traditional text tools** (grep, sed, cat, etc.) when working with the cmpr codebase.\n"
  "\n"
  "**Why use cmpr commands**:\n"
  "- They understand the block structure\n"
  "- They are way more efficient, because you can get directly from the root block to any other block in the codebase in ~ log n steps\n"
  "\n"
  "**Navigation Commands**:\n"
  "- `cmpr --print-block '#id'` - Show entire block (NL + PL)\n"
  "- `cmpr --print-comment '#id'` - Show only NL comment\n"
  "- `cmpr --print-code '#id'` - Show only PL code\n"
  "- `cmpr --grep 'pattern'` - Search for pattern across blocks (PREFER THIS for searching)\n"
  "- `cmpr --find-block 'search_term'` - Find blocks containing text (deprecated, use --grep instead)\n"
  "- `cmpr --files-blocks` - Overview of all blocks in the project\n"
  "\n"
  "**List blocks in a specific file**:\n"
  "```bash\n"
  "cmpr --files-blocks | grep -A 1000 'file: rvs_lib.py' | grep -B 1000 -m 1 '^file:' | head -n -1\n"
  "```\n"
  "\n"
  "This grep pipeline extracts just the blocks for a specific file from the `--files-blocks` output.\n"
  "\n"
  "**Editing Commands**:\n"
  "- `cmpr --replace '#id'` - Replace entire block (NL + PL) from stdin; for blocks with no PL part, this effectively replaces just the NL\n"
  "- `cmpr --replace-comment '#id'` - Replace only NL part\n"
  "- `cmpr --replace-code '#id'` - Replace only PL part\n"
  "- `cmpr --rewritepl '#id'` - Regenerate PL from NL using nl2pl\n"
  "- `cmpr --after '#id'` - Add a new block after the given block ID, reading contents from stdin\n"
  "\n"
  "There should be --before but there isn't.\n"
  "This is annoying when you want to make a new block be the first one in a file.\n"
  "The workaround is: cat the new block then the current first block of the file separated by a newline, into --replace <id of first block>.\n"
  "\n"
  "**INBOX Pattern for Staging New Blocks**:\n"
  "\n"
  "The #INBOX block serves as a staging area for new blocks during development:\n"
  "\n"
  "```bash\n"
  "# Add a new block after INBOX\n"
  "<something> | cmpr --after '#INBOX'\n"
  "# Check the INBOX\n"
  "cmpr --files-blocks | grep -A 1000 'file: INBOX.c' | grep -B 1000 -m 1 '^file:' | head -n -1\n"
  "```\n"
  "\n"
  "This pattern:\n"
  "- Provides a known location for rapid iteration without deciding final placement\n"
  "- Keeps new work (experience reports, experiments) organized\n"
  "- Blocks in INBOX should be moved to appropriate locations during review sessions\n"
  "- Use the block moving pattern (save, delete, insert) to relocate staged blocks\n"
  "\n"
  "When to use INBOX:\n"
  "- Experience reports documenting work sessions\n"
  "- Experimental or exploratory blocks\n"
  "- New documentation blocks whose final home is unclear\n"
  "- Any block where you want to defer the navigation structure decision\n"
  "\n"
  "## Reordering/Moving Blocks\n"
  "\n"
  "**Adding a block at the START of a file** (no --before exists yet):\n"
  "```bash\n"
  "# Create new content with overview block, then concat existing first block, then replace\n"
  "cat new_block.txt <(cmpr --print-block '#first_block_id') | cmpr --replace '#first_block_id'\n"
  "```\n"
  "\n"
  "To move a block to a different position in a file:\n"
  "\n"
  "1. Save the block to a temp file: `cmpr --print-block '#block_id' > /tmp/block.txt`\n"
  "2. Delete the block from its current position: `echo \"\" | cmpr --replace '#block_id'`\n"
  "3. Insert it at the new position: `cat /tmp/block.txt | cmpr --after '#target_block_id'`\n"
  "\n"
  "**IMPORTANT**: Never create temporary duplicates of blocks (adding before deleting) because having duplicate block IDs results in undefined behavior. Always delete first, then add at the new location.\n"
  "\n"
  "**Example - Moving a block**:\n"
  "```bash\n"
  "# Step 1: Save block\n"
  "cmpr --print-block '#block_to_move' > /tmp/block.txt\n"
  "\n"
  "# Step 2: Delete from current location\n"
  "echo \"\" | cmpr --replace '#block_to_move'\n"
  "\n"
  "# Step 3: Insert at new location (after the block that should precede it)\n"
  "cat /tmp/block.txt | cmpr --after '#preceding_block'\n"
  "```\n"
  "\n"
  "**Navigating the Codebase**:\n"
  "\n"
  "All navigation MUST start from the root block and follow block references:\n"
  "\n"
  "1. **Start at the root block**: Read it to see the main navigation hubs\n"
  "2. **Use 2-3 hops**: You should be able to reach any area of the codebase in 2-3 `--print-comment` calls by following block references\n"
  "3. **The root block is the map**: It provides access to all major subsystem hubs (implementation details, agent framework, event system, libraries, etc.)\n"
  "\n"
  "**Navigation Principle**: If you cannot reach the blocks you need from the root block by following direct references, that is a PROBLEM. DO NOT work around it by using search commands. Instead:\n"
  "1. STOP and inform the user that navigation is broken\n"
  "2. Help fix the navigation structure by adding appropriate overview blocks or references\n"
  "3. Only proceed with the original task after navigation is fixed\n"
  "4. If the only thing you do is fix the navigation, so that you can find what you need to in 2-3 hops from root, and then you end the session and the programmer commits your change, that was a good session.\n"
  "\n"
  "### NL/PL Synchronization\n"
  "\n"
  "**Standard Workflow**:\n"
  "1. Edit ONLY the NL using `cmpr --replace-comment '#blockid'` which takes new contents on stdin.\n"
  "   - you should always have the previous NL in scope, otherwise do a --print-comment first, then make your changes\n"
  "2. Run `cmpr --rewritepl '#block_id'` to regenerate PL from NL\n"
  "3. Run `cmpr --print-code '#block_id'` to verify the generated PL looks correct\n"
  "4. Test the changes with `dist/cmpr`\n"
  "\n"
  "**When to Manually Maintain PL**:\n"
  "- Only mark a block as \"Manually maintained\" if you MUST write PL directly\n"
  "- Add \"Manually maintained.\" as the last line of the NL comment\n"
  "- This is rare and should be avoided when possible - prefer letting the system generate code\n"
  "\n"
  "**CRITICAL: NL Precision for nl2pl**:\n"
  "- The nl2pl system can generate correct code, but ONLY when the NL is unambiguous\n"
  "- Vague specifications lead to incorrect implementations\n"
  "- When performance or correctness matter, be VERY explicit about:\n"
  "  - Exact algorithms (e.g., \"BFS traversal calling cmpr --print-comment for each block\")\n"
  "  - Data structures (e.g., \"block-scoped graph, not file-scoped\")\n"
  "  - What NOT to do (e.g., \"don't scan entire files, only individual NL comments\")\n"
  "- If the generated PL is wrong, the NL was probably ambiguous - fix the NL, not the PL\n"
  "\n"
  "**Important Notes**:\n"
  "- `cmpr` (usually `/usr/local/bin/cmpr`) is the installed system version - use for reading/inspecting\n"
  "- `dist/cmpr` is the locally built binary from `make` - use for testing your changes\n"
  "- After modifying source code, always test with `dist/cmpr`, not the system `cmpr`\n"
  "- The interactive `r` command in the TUI does the same as `--rewritepl`\n"
  "\n"
  "### Testing Changes\n"
  "\n"
  "**Build System**:\n"
  "- Run `make` to build `dist/cmpr`\n"
  "- Check build timestamp: `dist/cmpr --version`\n"
  "- The Makefile will compile changed source files and link the binary\n"
  "\n"
  "**Testing Binary**:\n"
  "- Always test with `dist/cmpr`, not the system `cmpr` command\n"
  "- The system `cmpr` at `/usr/local/bin/cmpr` will be older\n"
  "- After code changes, run `make` to rebuild before testing\n"
  "\n"
  "### Code Conventions\n"
  "\n"
  "It should be possible to reach any block by following \"Justifies: \" lines, or explicit blockid mentions, starting from the root block.\n"
  "\n"
  "**Duplicate Block References**: It is perfectly fine for a block ID to be mentioned multiple times in a parent block. Duplicate references do not cause any problems and are sometimes useful for documentation clarity.\n"
  "\n"
  "**Important Note**:\n"
  "We are still building up the graph from the root block to all the other blocks.\n"
  "If you cannot reach the blocks that you need from the root block by following direct references, that's a problem.\n"
  "DO NOT work around it but always stop and make some edits.\n"
  "\n"
  "The basic idea is this:\n"
  "The root block should give a high-level overview of the parts of the project.\n"
  "If you know what you're trying to do (e.g. add feature X) then you should be able to determine where the relevant code is by just following blockids and using --print-comment 2-3 times, which makes things very efficient.\n"
  "When that's not the case, you should probably ask the programmer about what needs to be improved in the structure, because we're still building this system out.\n"
  "\n"
  "Similarly, if a cmpr command doesn't work or doesn't do what you expect, don't fall back to using other tools, but always let the programmer know and we'll fix it together.\n"
  "We're using cmpr to build cmpr itself here, so if cmpr doesn't work right, then we always fix that before continuing with whatever we were doing before.\n"
  "\n"
  "### Project Configuration\n"
  "- Configuration is stored in `.cmpr/conf`\n"
  "- Bootstrap scripts provide AI context: `./bootstrap.sh` -- this is obsolete\n"
  "- Default model and build commands are configurable per project\n"
  "\n"
  "## Core Architecture\n"
  "\n"
  "### Single-Tier C System\n"
  "This is a pure C application with no web frontend or HTTP server:\n"
  "- **`cmpr.c`** - Main application: block database, CLI commands, and terminal UI (TUI). Includes hardcoded prompt templates for nl2pl code generation.\n"
  "- **`spanio.c`** - Custom I/O library using span-based string handling\n"
  "- **`Makefile`** - Build system (details documented in blocks)\n"
  "\n"
  "### Block-Based Code Organization\n"
  "- Code is organized into discrete \"blocks\" with IDs like `#block_name`\n"
  "- Each block contains:\n"
  "  - **NL Part**: Natural language comment (source of truth)\n"
  "  - **PL Part**: Programming language code (generated from NL)\n"
  "- Block references (`@other_block`) provide context dependencies\n"
  "- Transitive references create dependency graphs\n"
  "\n"
  "### Revision System\n"
  "- Every code change is automatically versioned in `.cmpr/revs/`\n"
  "- Uses SipHash checksums for content integrity\n"
  "- Complete history tracking with timestamps\n"
  "- There is an 'rvs' command which lets us interact with the revisions; we'll expand this section later; it's not very useful yet.\n"
  "\n"
  "## Key Components\n"
  "\n"
  "### cmpr.c (Main Application)\n"
  "- **CLI Mode**: Command-line interface with flags like `--grep`, `--print-block`, `--replace`, etc.\n"
  "- **Terminal UI (TUI)**: Interactive mode with single-keystroke commands (`j/k/g/G` for navigation, `r` for rewrite, `B` for build)\n"
  "- **Block Database**: Parses and manages blocks across all source files\n"
  "- **Operations**: Block navigation, code generation (nl2pl), building, search, history\n"
  "- **LLM Integration**: Calls external LLM APIs for nl2pl code generation\n"
  "\n"
  "### spanio.c (I/O Library)\n"
  "- Custom I/O library using span-based string handling with `.buf` and `.end` pointers\n"
  "- Arena allocation avoiding malloc overhead\n"
  "- Efficient string operations without null-terminator dependencies\n"
  "\n"
  "### Prompt System\n"
  "- LLM prompt templates for nl2pl (natural language to programming language) conversion are hardcoded in cmpr.c\n"
  "- Prompt functions (pt_nl2pl_rewrite, pt_agreement, etc.) return template strings\n"
  "- Simplified from previous generation-based system to avoid circular build dependencies\n"
  "\n"
  "## Development Patterns\n"
  "\n"
  "### Natural Language Programming Workflow\n"
  "1. Write English descriptions in block comments\n"
  "2. AI converts to working code in target language\n"
  "3. System maintains consistency between documentation and code\n"
  "4. Focus on higher-level architectural decisions\n"
  "\n"
  "### Agent System and Decision Tracking\n"
  "\n"
  "**Running Agents**:\n"
  "\n"
  "To execute an agent:\n"
  "```bash\n"
  "cmpr --print-code '#agent_block_id' | bash\n"
  "```\n"
  "\n"
  "To list all available agents:\n"
  "```bash\n"
  "dist/cmpr --agents\n"
  "```\n"
  "\n"
  "Example - run an agent:\n"
  "```bash\n"
  "cmpr --print-code '#agent_block_id' | bash\n"
  "```\n"
  "\n"
  "Navigation to agents:\n"
  "1. Start at root block → follow references to agent hub\n"
  "2. The agent hub lists all agent blocks and explains how to run them\n"
  "\n"
  "**Agent Architecture**:\n"
  "- An agent = **Predicate (Want)** + **Step Function (CHECK/FIX)**\n"
  "- Wants establish event spaces: {desired state, complement}\n"
  "- Agents verify and maintain wants through CHECK and FIX modes\n"
  "\n"
  "**Four Decision States** (tracked → checked → assisted → owned):\n"
  "1. **Tracked**: We record the want but don't verify it\n"
  "2. **Checked**: We can determine if criteria is met\n"
  "3. **Assisted**: We can offer help with fixing it\n"
  "4. **Owned**: We automatically maintain the want\n"
  "\n"
  "**Implementing Agents**:\n"
  "- Create two blocks: predicate block + step function block\n"
  "- Both executable via `cmpr --print-code '#blockid' | sh` or `bash`\n"
  "- Step functions report state using SN notation\n"
  "- Example pattern: predicate block + CHECK mode block + FIX mode block\n"
  "- Agents integrate with the event system (T) to record activity\n"
  "\n"
  "**SN Notation** for confidence levels:\n"
  "- 255 bits = definitional (statement is defined to be true)\n"
  "- 20 bits = ~1 million to 1 confidence (virtually certain)\n"
  "- 0 bits = describes possible event with no support\n"
  "\n"
  "### Event System (T/E/S)\n"
  "\n"
  "The event system provides temporal reasoning capabilities through tracking events in \"transient memory\" (T).\n"
  "\n"
  "**Key Concepts**:\n"
  "- **T (transient memory)**: Current event state, automatically persisted to `.cmpr/T`\n"
  "- **E (events)**: Individual event strings with associated strength values\n"
  "- **S (strength)**: Binary log odds representing bits of support for a proposition\n"
  "- **SN lines**: Format is `\"event_string\" <strength>.` where interior quotes are NOT escaped\n"
  "\n"
  "**CLI Commands**:\n"
  "- `cmpr --T0` - Reset T to empty state\n"
  "- `cmpr --event \"string\" --strength 255` - Add event to T (currently only strength 255 supported)\n"
  "- `cmpr --T` - Print current T state as SN lines\n"
  "- `cmpr --memorize` - Save timestamped snapshot of T to `.cmpr/events/`\n"
  "- `cmpr --recall` - Search snapshots using current T as query, load matching snapshot with full context\n"
  "\n"
  "**Implementation Details**:\n"
  "- T persists automatically to `.cmpr/T` on every change\n"
  "- Events are loaded on startup and saved after modifications\n"
  "- Memorize creates timestamped snapshots (YYYYMMDD-HHMMSS-nanos format)\n"
  "- Recall searches snapshots (newest first) for ones containing any query event from current T, then loads all events from the matching snapshot\n"
  "- Event strings can contain any characters including quotes (per SN spec)\n"
  "- Duplicate events update strength rather than creating duplicates\n"
  "\n"
  "**SN Format Specification**:\n"
  "Per the SN notation convention:\n"
  "- SN lines begin with `\"` and end with `\" <digits>.`\n"
  "- Interior double quotes are NOT escaped\n"
  "- Parse by finding `\" <digits>.` pattern at end of line\n"
  "- Everything between opening `\"` and final `\" <digits>.` is the event string\n"
  "\n"
  "**Event System Workflow and Design Intent**:\n"
  "\n"
  "NOTE: This section describes intended design patterns that are still being validated through actual use.\n"
  "\n"
  "CRITICAL UNDERSTANDING: T is \"transient memory\" - the name and the existence of `--T0` (clear T) reveal the design intent.\n"
  "\n"
  "T is meant to be CLEARED between work sessions. It holds CURRENT context, not ALL historical state.\n"
  "\n"
  "Typical workflow:\n"
  "```bash\n"
  "# Clear T for new work\n"
  "cmpr --T0\n"
  "\n"
  "# Set context (e.g., which block we're examining)\n"
  "cmpr --event \"The block id is: #foo\" --strength 255\n"
  "\n"
  "# Add facts about current context\n"
  "cmpr --event \"The block author is: Alice\" --strength 255\n"
  "cmpr --event \"The block needs refactoring\" --strength 255\n"
  "\n"
  "# Save snapshot for historical record\n"
  "cmpr --memorize\n"
  "\n"
  "# Repeat for next block/context\n"
  "```\n"
  "\n"
  "Event Pattern Usage:\n"
  "\n"
  "The **variable pattern** is the correct approach:\n"
  "```\n"
  "\"The block id is: #foo\" 255.\n"
  "\"The block is reachable\" 255.\n"
  "\"The block author is: Alice\" 255.\n"
  "```\n"
  "\n"
  "T holds context for ONE entity at a time. To track multiple entities, LOOP:\n"
  "```bash\n"
  "for block in $all_blocks; do\n"
  "  dist/cmpr --T0\n"
  "  dist/cmpr --event \"The block id is: $block\" --strength 255\n"
  "  dist/cmpr --event \"The block is reachable\" --strength 255\n"
  "  dist/cmpr --memorize\n"
  "done\n"
  "```\n"
  "\n"
  "WRONG APPROACHES (do not use):\n"
  "\n"
  "1. **\"Embedded pattern\"** - trying to avoid deduplication:\n"
  "   ```\n"
  "   \"Block #foo is reachable\" 255.  # WRONG\n"
  "   \"Block #bar is unreachable\" 255.  # WRONG\n"
  "   ```\n"
  "   This tries to load all entities into one T state, violating T's transient design.\n"
  "\n"
  "2. **Loading hundreds of events into one T state**:\n"
  "   Fights the design. T is not a database for all historical state.\n"
  "\n"
  "3. **\"Alternative mechanisms\"** (files, databases, etc.):\n"
  "   The intended pattern is to use the T workflow correctly:\n"
  "   Loop with --T0, set context, add events, --memorize.\n"
  "\n"
  "When designing solutions:\n"
  "- If you find yourself fighting `--T0` or avoiding `--memorize`, reconsider the approach\n"
  "- T is for CURRENT work context, snapshots (via --memorize) are for HISTORICAL queries\n"
  "- Pay attention to what system commands exist - they reveal design intent\n"
  "- The existence of --T0 means T is MEANT to be cleared regularly\n"
  "\n"
  "## File Structure\n"
  "\n"
  "- **Core Application**: `cmpr.c` (main application with CLI and TUI, includes hardcoded prompt templates)\n"
  "- **I/O Library**: `spanio.c` (span-based string handling)\n"
  "- **Staging Area**: `INBOX.c` (staging area for new blocks)\n"
  "- **Configuration**: `.cmpr/conf` (project configuration)\n"
  "- **Build System**: `Makefile` (build system details in blocks)\n"
  "- **Revisions**: `.cmpr/revs/` (automatic versioning)\n"
  "- **Events**: `.cmpr/events/` (event system snapshots), `.cmpr/T` (current transient memory)\n"
  "- **Reports**: `public_html/` (generated HTML reports for system visibility)\n"
  "- **Build Output**: `dist/cmpr` (compiled binary)\n"
  "\n"
  "## Common Pitfalls and Process Reminders\n"
  "\n"
  "**CRITICAL: Always Use cmpr Commands**\n"
  "\n"
  "After exiting planning mode or when context-switching, it's easy to forget cmpr commands exist and fall back to traditional file editing (Write, Edit tools). This makes you 10x slower and less token-efficient.\n"
  "\n"
  "**Before touching ANY file**:\n"
  "1. Check if it's block-managed: `cmpr --files-blocks | grep filename`\n"
  "2. If yes, use ONLY cmpr commands: `--print-comment`, `--replace`, `--after`\n"
  "3. NEVER use Write/Edit tools on block-managed files\n"
  "\n"
  "**Common mistakes**:\n"
  "- ❌ Using Task tool with Explore subagent to \"explore the codebase\" → ✅ Start at root block and navigate\n"
  "- ❌ Using `Write` to create new blocks → ✅ Use `cmpr --after <block_id>`\n"
  "- ❌ Using `Edit` to modify existing blocks → ✅ Use `cmpr --replace '#block_id'`\n"
  "- ❌ Using `Read` + manual parsing → ✅ Use `cmpr --print-comment '#block_id'`\n"
  "- ❌ Using `grep`/`find` to locate code → ✅ Use `cmpr --grep` or navigate from root\n"
  "- ❌ Manually reading .cmpr/revs files → ✅ Use existing rvs indices and helpers\n"
  "- ❌ Starting ANY task without reading root block first → ✅ Always start by reading the root block to see navigation hubs\n"
  "- ❌ Piping commands into `--replace-code` without testing → ✅ Test with `wc -l`, then `grep`, THEN replace\n"
  "- ❌ Grepping or filtering `make` output → ✅ Read it directly - it's a serious build system, not npm\n"
  "- ❌ Creating blocks without knowing final location → ✅ Use `cmpr --after '#INBOX'` and move later\n"
  "\n"
  "**CRITICAL: Navigation Structure**\n"
  "\n"
  "Every block MUST be reachable from #root in ≤2 hops. This is a core want maintained by the root agent.\n"
  "\n"
  "When creating new blocks:\n"
  "1. ❌ **WRONG**: Create block in INBOX, leave it there permanently\n"
  "2. ✅ **CORRECT**: Create block AND immediately integrate it into navigation:\n"
  "   - Add reference to relevant hub block\n"
  "   - OR create new hub if starting a new subsystem\n"
  "   - OR use INBOX only for temporary/experimental blocks\n"
  "\n"
  "The navigation structure IS the codebase organization. Breaking navigation means:\n"
  "- The block is effectively lost (not discoverable)\n"
  "- It won't appear in anyone's mental model of the system\n"
  "- The #root want is violated\n"
  "\n"
  "Fix navigation BEFORE implementing anything else. If you cannot reach the blocks you need in 2 hops from #root by following references, that is a PROBLEM that must be fixed first, not worked around.\n"
  "\n"
  "**Block structure patterns**:\n"
  "- ❌ One block containing multiple function implementations → ✅ Overview block listing child blocks\n"
  "- Each block should either be:\n"
  "  - An overview/index block (NL only, listing other blocks)\n"
  "  - A single implementation block (NL + PL for one function/feature)\n"
  "- When you see a block with many functions, refactor it into an overview + individual blocks\n"
  "- Don't be afraid to refactor a block into two new blocks.\n"
  "  When you do this: make the first block the right size and the second block contain everything else.\n"
  "  If it can't be divided up that way, don't refactor it.\n"
  "  Use the _2 prefix for the second block unless there's clearly something better to call it (like draw_the_rest_of_the_fucking_owl).\n"
  "  When you do that, don't change anything else, and wrap up the session and commit the change soon if you can.\n"
  "\n"
  "**When working with existing infrastructure**:\n"
  "- DON'T reimplement helpers that already exist (like checksum functions)\n"
  "- DO navigate from root block to find existing functionality\n"
  "- DO check existing index catalogs before designing new indices\n"
  "- DO look at similar command blocks for patterns\n"
  "\n"
  "Never be afraid to go back to the root block and look for something else.\n"
  "\n"
  "**Plan mode amnesia**:\n"
  "- Planning mode can last multiple turns - easy to forget the cmpr workflow\n"
  "- When exiting plan mode, IMMEDIATELY verify: \"Am I working with block-managed files?\"\n"
  "- Refresh memory of cmpr commands before starting implementation\n"
  "\n"
  "## Session Workflow\n"
  "\n"
  "**Starting a session:**\n"
  "\n"
  "Check current T state to see recent work:\n"
  "```bash\n"
  "dist/cmpr --T\n"
  "```\n"
  "\n"
  "T contains events from recent work sessions. Check for:\n"
  "- Experience report events: `\"The experience report is: #blockid\"`\n"
  "- Agent execution results: `\"Agent: \"`, `\"Status: \"`, etc.\n"
  "- Want tracking: `\"The want is: \"`, `\"Automation state: \"`\n"
  "\n"
  "To load context from a previous session:\n"
  "```bash\n"
  "dist/cmpr --T0  # Clear current T\n"
  "dist/cmpr --event \"The experience report is: #blockid\" --strength 255\n"
  "dist/cmpr --recall  # Loads all events from that session\n"
  "dist/cmpr --T  # View loaded context\n"
  "```\n"
  "\n"
  "**Ending a session:**\n"
  "\n"
  "1. Write experience report (see Experience Reports section below)\n"
  "2. Add experience report to INBOX: `cat report.txt | cmpr --after <inbox_block_id>`\n"
  "3. Add event to T with block ID:\n"
  "   ```bash\n"
  "   dist/cmpr --event \"The experience report is: #experience_report_block_id\" --strength 255\n"
  "   ```\n"
  "4. Save snapshot:\n"
  "   ```bash\n"
  "   dist/cmpr --memorize\n"
  "   ```\n"
  "\n"
  "This creates a queryable checkpoint. Future sessions can use `--recall` to load all events from this session, providing full context about what was done, which agents ran, what state was observed, etc.\n"
  "\n"
  "**Pattern:**\n"
  "- T is transient memory for CURRENT work\n"
  "- Snapshots (via --memorize) preserve historical context\n"
  "- Experience report events enable finding session work later\n"
  "- Each memorized snapshot contains: agent events + want tracking + experience report reference\n"
  "\n"
  "## Experience Reports\n"
  "\n"
  "**When to Write**:\n"
  "- At the end of every work session\n"
  "- When completing significant tasks (planning, implementation, debugging)\n"
  "- When stopping work on something that's not finished\n"
  "\n"
  "**What to Include**:\n"
  "- Session goal\n"
  "- What was accomplished (detailed)\n"
  "- What works\n"
  "- Known issues/blockers\n"
  "- Next steps\n"
  "- Full context for resuming work\n"
  "\n"
  "**Naming Pattern**:\n"
  "- Format: `#<agent>_experience_report_<topic>_YYYYMMDD_N`\n"
  "- Agent names: claude, codex, or other agents\n"
  "- Example: `#claude_experience_report_<descriptive_topic>_YYYYMMDD`\n"
  "\n"
  "**Response Format**:\n"
  "- Chat responses should be ONE LINE referencing the experience report\n"
  "- Example: \"See #experience_report_block_id\"\n"
  "- ALL details, summaries, and context go in the experience report block\n"
  "- Keep conversation clean and searchable - detail lives in blocks\n"
  "\n"
  "**Storage**:\n"
  "- Experience reports go in INBOX initially: `cat report.txt | cmpr --after '#INBOX'`\n"
  "- Can be moved to permanent locations later during review\n"
  "- Or left in INBOX as temporal documentation\n"
  ;

int bootstrap_content_len = sizeof(bootstrap_content_data) - 1; // -1 for null terminator

span get_bootstrap_content_span() {
    span s;
    s.buf = bootstrap_content_data;
    s.end = bootstrap_content_data + bootstrap_content_len;
    return s;
}
