rope rope_new(size_t);
int rope_isnull(rope); // 1 if initialized, 0 otherwise
void rope_release(rope*);
span rope_alloc_atleast(rope*,size_t);
void event_add_internal(span event_str, unsigned char strength);
spans dir_listing(span dirname);
void event_parse_sn(span content);
void event_parse_sn(span);
checksums load_revblock_checksums(int revblock_idx);
spans load_revblock_ids(int revblock_idx);
Partial partial_sp_sp(span, void(*)(span,span));
Partial partial_0_sp(void(*)(span));
void apply_partial(Partial,span);
void start_search();
void perform_search();
void finalize_search();
void search_forward();
void search_backward();
int find_block(span); // find first block containing text
void start_ex();
void handle_ex_command();
void addfile(span);
void addlib(span);
void ex_help();
void set_highlight();
void reset_highlight();
void select_model();
int select_menu(spans opts, int sel); // allows selecting from a short list of options
void print_menu(spans, int);
void page_down();
void page_up();
void print_current_blocks();
void render_block_range(int,int);
void print_physical_lines(span, int);
int print_matching_physical_lines(span, span);
span count_physical_lines(span, int*);
void print_multiple_partial_blocks(int,int);
void print_single_block_with_skipping(int,int);
void cmpr_init(); // handles --init
void print_block(int);
void print_comment(int);
void print_code(int);
int count_blocks();
void clear_display();
void get_code(); // read and index current code
void get_revs(); // read and index revs
spans find_blocks(span); // find the blocks in a file
spans find_blocks_language(span file, span language); // find_blocks helper function dispatching on language
void find_all_lines(); // like find_all_blocks, but for lines; applies to the whole project
void index_block_ids();
void ingest(); // updates everything that needs to be updated after code has changed
int main(int, char**);
void init();
void read_(int argc, char** argv);
void call_llm(span model, json messages, llm_message_handler cb);
void read_openai_key();
void read_anthropic_key();
span filename_template(span);
span assoc_spans_lookup(spans, span);
spans filename_variables();
network_ret call_gpt(json messages, span model);
network_ret call_gpt_curl(span req, span resp, span err);
network_ret call_ollama(json messages, span model);
network_ret call_ollama_curl(span req, span resp, span err);
network_ret call_anthropic(json messages, span model);
network_ret call_anthropic_curl(span req, span resp, span err);
span get_bootstrap_content_span();
void handle_args(int argc, char **argv);
void handle_snapshot_join(span es1, span es2);
span help_text_nl2pl(span);
void print_physical_lines(span block, int lines_to_print);
void print_files_blocks();
void inp_sanity_checks();
checksum selected_checksum(span);
checksum compute_file_checksum(span path);
int checksum_is_known(checksum cs);
void replace_known_checksum(checksum old_cs, checksum new_cs, span filename);
void save_external_rev(int file_index, struct timespec ts);
span unique_rev_path(struct timespec ts);
void ingest();
void index_block_ids();
spans ids_for_block(span);
int block_for_span(span);
span id_for_block(span);
checksum current_block_checksum();
void set_current_block(int);
void block_id_jump();
spans refs_for_block(span block);
spans mentions_for_block(span block);
spans referrers_to_block(int block_idx);
int refs_menu(int block_idx, spans breadcrumb);
void block_refs_jump();
span get_revdir();
void get_revs_2();
span read_file_into(span filename, rope*);
int get_revs_cache_get(span bname, span rev_contents);
checksum scan_checksum(span);
int scan_int(span*);
int parse_int(span); // parse int without mutating
int scan_hex(span*);
int parse_hex(span);
int parse_revfile_cache(span bname, span rev_cache, span rev_contents);
void parse_section_header_line(int *failure, int *section_type, int *block_number, span *rev_cache);
void parse_blocks_lines(int *failure, time_t timestamp, int n_blocks, span rev_contents, span* rev_cache);
void parse_scs_lines(int *failure, int rev_block_idx, span* rev_cache);
void parse_ids_lines(int *failure, int rev_block_idx, span* rev_cache);
void get_revs_cache_put(checksums* working_set, span bname, span content);
void pr_revinfo(span language, spans blocks, int prev_n_revblocks, span contents);
void pr_checksum(checksum);
void pr_relative_span(span,span);
span prs_checksum(checksum);
int getkey();
void sbv_display(sbv_state* sbvs);
void sbv_populate(sbv_state* sbvs);
int block_id_match(spans curr_ids, spans rev_ids);
int rev_block_match(sbv_state* sbvs, int revblock_idx);
void select_block_version();
checksums sorted_line_checksums(span);
int cksums_intersection(checksums,checksums);
spans find_blocks_language_c(span);
spans find_blocks_language_markdown(span);
time_t parse_rev_fname(span);
spans find_blocks_language_python(span);
spans find_blocks_language(span, span);
char getch();
void main_loop();
void render_empty_project_state();
void render_empty_file_state();
void handle_keystroke(char);
void delete_block();
void keyboard_help();
span find_last_deleted_block();
void find_all_deleted_blocks();
void paste_after();
void paste_before();
void handle_j();
void handle_k();
void handle_g();
void handle_G();
int first_block_in_file(int);
int last_block_in_file(int);
void print_menu(spans,int);
int select_menu(spans,int);
int select_menu_searchable(spans options, int initial_index);
void bootstrap();
void print_ruler();
span get_debug_info();
int print_matching_physical_lines(span block, span match);
void handle_conf_language(span);
void handle_conf_file(span);
void handle_conf_file_ro(span);
int file_is_readonly(int file_idx);
void parse_config();
void save_conf_files();
void save_conf();
void check_dirs();
void check_conf_vars();
void ensure_conf_var(span* var, span message, span default_value);
void edit_current_block();
void insert_block_after();
void insert_block_before();
span tmp_filename();
int launch_editor(char* filename);
int file_for_block(span);
span current_block_language();
span guess_language_from_filename(span);
span language_for_block(span block);
void handle_edited_file(char *filename);
void new_rev(span tmp_filename, int file_index);
void update_projfile(int file_index, span tmp_filename, span rev_path);
void send_to_llm(span, llm_message_handler cb);
void llm_stdout_handler(span);
void handle_llm(void);
void handle_openai_response(span response, llm_message_handler cb);
void handle_ollama_response(span response, llm_message_handler cb);
void handle_anthropic_response(span response, llm_message_handler cb);
int find_comment_end_c(span);
int find_comment_end_python(span);
span block_comment_part(span);
span block_code_part(span);
spans get_palette();
void apply_prompt(span prompt_name);
span get_prompt_template(span name);
void agreement();
void agreement_to_nl_diff();
void output_template_var(spans* ctx, span human_name);
span lookup_output(span output_of);
span expand_template(span template, spans vars);
void print_template_literal(span);
spans current_block_template_vars();
void eval_template_variable(span, spans);
spans parse_template(span);
void print_block_ofra(int index);
void content_index(span search_text);
int block_from_arg(char* arg);
int block_id_arg(span block_id_or_int);
void handle_run(char* run_block_id);
void handle_agent_run(char* agent_name, char* mode);
void handle_agents();
void handle_install_agent(char *agent_name);
void handle_install_script(char *script_name);
span get_help_text(span topic);
span get_agent_script(span name);
void handle_help_topic(char *topic);
void handle_prompt(int block_idx);
void handle_checksum(void);
void handle_event_large_stdin(int strength);
void handle_event_large_file(span path, int strength);
void handle_wants(int show_blocks);
void handle_wants_status();
void handle_agents_wants();
void handle_wants_dashboard();
void handle_work(char *event_arg);
void handle_trace();
void handle_status();
void handle_event_report();
void handle_export_docs();
void handle_es();
void handle_P();
void grep_blocks(span pattern);
void after(span arg);
void replace(span arg);
void handle_replace_current(void);
void replace_comment(span);
void replace_code(span);
void expand_block(int idx);
int block_by_id(span id_no_hash);
void ex_expand();
void ex_reload();
void ex_config();
void ex_allfiles();
void ex_addfile(span file_path);
void ex_addlib(span lib_path);
span blockref_id(span ref);
span blockref_fname(span ref);
span language_comment_starter(span language);
span language_comment_ender(span language);
span expand_refs_2(span,span);
void expand_refs_2_rec_both   (span block, span transform, spans* already, int comment_context, int depth);
void expand_refs_2_rec_body(span block, span transform, spans* already, int comment_context, int depth);
void expand_refs_2_rec_context(span block, span transform, spans* already, int comment_context, int depth);
span chase_ref_2(span);
span strip_markdown_codeblock(span);
void send_to_clipboard(span);
span normalize_path_for_match(span);
int paths_match_for_block_map(span, span);
int parse_block_map_entry(span, span*, int*, int*, span*);
spans block_ids_for_file_line(span, span, int);
int parse_compiler_error_line(span, span*, int*);
void replace_block_code_part(span);
void output_save(span operation, span message);
llm_message_handler make_output_saver(span operation);
void generic_output_save(span operation, span message);
void agreement_SAV(span);
int span_cmp_wrapper(const void*, const void*);
void get_outputs();
spans dir_listing(span dirname);
spans read_output_headers(span bname);
span read_output_body(span bname);
void replace_block(span new_block);
llm_message_handler simple_message_handler(void(*f)(span));
void nl2pl_rewrite();
void pl2nl_rewrite();
void pl2nl_rewrite_cb(span message);
void nl2algo();
void agreement_to_pl_diff();
void summarize_block();
void handle_learn(span es1, span es2);
void handle_log_stochastic_count_joint();
void compile();
span find_prev_rev(span block_id, int file_idx);
void replace_structure_detect(span old_id, span new_range, span prev_block_id, span prev_rev_path, int file_idx);
void replace_through(span arg1, span arg2);
void handle_E();
void handle_induced(char *es_name);
void handle_induced_single(char *event_str);
void handle_lpp(char *es1, char *es2);
void handle_es_create(char *name, char *pattern);
void handle_history(span blockid, double log_gap_factor, int limit);
void handle_history_blockid(span blockid, double log_gap_factor, int limit);
void handle_history_recent(double log_gap_factor, int limit);
span span_dup(span s);
int check_file_changed(int file_index);
void reload_file(int file_index);
void handle_args(int argc, char **argv);
span help_text_agent_qa(span);
span help_text_topics(span);
span block_foo(span);
span help_text_summary(span);
span help_text_basic(span);
span help_text_blocks(span);
span help_text_inbox(span);
span help_text_editing(span);
span help_text_search(span);
span help_text_events(span);
span help_text_agents(span);
span help_text_claude_setup(span);
span agent_script_claude(span);
span help_text_reports(span);
span help_text_wants(span);
span help_text_history(span);
void agreement_SAV(span);
void agreement();
span script_Tcks(span);
span script_time(span);
span script_blockid(span);
span script_next_block(span);
span script_next_rev(span);
span script_next_want(span);
span script_wantid(span);
span script_block(span);
span script_build_warnings_check(span);
span script_checksum(span);
span script_help_argtable_check(span);
span script_checksum_check(span);
span script_fdecls(span);
span script_loop(span);
span script_read_block_list(span);
span script_read_block_order(span);
span script_read_rev_order(span);
span script_read_want_order(span);
span script_want_status(span);
span script_process_want(span);
span script_process_all_wants(span);
span script_train_want_state_pattern(span);
span script_nl2pl_block_check(span);
span get_script(span name);
span script_patterns(span);
