/* #generate_help_topics

span get_help_text(char *topic);

Generate help_topics.c from help text blocks in INBOX.c.

This script extracts help text from blocks like #help_text_basic, #help_text_events, etc.
and generates a C source file with:
- Function declaration in NL comment: span get_help_text(char *topic);
- u8 arrays for each topic containing the help text
- Helper function get_help_text(topic) definition

The function declaration in the NL comment gets extracted by fdecls.h.

*/


// Help text data arrays

u8 help_summary_data[] =
  "Usage: cmpr [--conf <filepath>] [--print-conf|--help|--init|--version] [(--print-block|--print-code|--print-comment|--expand-block) <id>] [--rewritepl <id>] [--prompt <id>] [--content-index <search>] [--grep <pattern>] [--count-blocks|--files-blocks|--print-all] [--after <id>] [(--replace|--replace-comment|--replace-code) <id>] [--run <block_id>] [--agents] [--agent-run <agent_name> <mode>] [--checksum] [--T0] [--event <string> --strength <value>] [--memorize] [--recall] [--T] [--snapshots] [--snapshot-view <timestamp>] [--event-spaces] [--wants] [--wants-status] [--agents-wants] [--wants-dashboard] [--event-report] [--export-docs]\n"
  "\n"
  "For help on available topics: cmpr --help topics\n"
  ;

u8 help_topics_data[] =
  "topics\n"
  "basic\n"
  "blocks\n"
  "editing\n"
  "search\n"
  "nl2pl\n"
  "events\n"
  "agents\n"
  "reports\n"
  "wants\n"
  "agent-qa\n"
  ;

u8 help_basic_data[] =
  "Basic Commands\n"
  "==============\n"
  "\n"
  "--help [topic]\n"
  "  Display help information.\n"
  "  Without topic: list all available topics.\n"
  "  With topic: show detailed help for that topic.\n"
  "  Example: cmpr --help events\n"
  "\n"
  "--version\n"
  "  Display version number and build timestamp.\n"
  "\n"
  "--init\n"
  "  Initialize .cmpr/ directory structure in current directory.\n"
  "  Creates necessary subdirectories and configuration files.\n"
  "  Cannot be combined with --conf.\n"
  "\n"
  "--conf <filepath>\n"
  "  Use alternate configuration file.\n"
  "  Specify before other commands to override default .cmpr/conf location.\n"
  "  Example: cmpr --conf /path/to/custom.conf --print-block '#root'\n"
  "\n"
  "--print-conf\n"
  "  Display current configuration settings.\n"
  "  Shows all configuration variables and their values.\n"
  ;

u8 help_blocks_data[] =
  "Block Viewing Commands\n"
  "======================\n"
  "\n"
  "--print-block <id>\n"
  "  Print complete block (both NL comment and PL code parts).\n"
  "  ID can be block ID like '#root' or one-based index.\n"
  "  Example: cmpr --print-block '#root'\n"
  "  Example: cmpr --print-block 1\n"
  "\n"
  "--print-comment <id>\n"
  "  Print only the NL (natural language) comment part of a block.\n"
  "  Useful for reading documentation without code.\n"
  "  Example: cmpr --print-comment '#argtable'\n"
  "\n"
  "--print-code <id>\n"
  "  Print only the PL (programming language) code part of a block.\n"
  "  Useful for extracting executable code.\n"
  "  Example: cmpr --print-code '#agent_root' | bash\n"
  "\n"
  "--expand-block <id>\n"
  "  Print block with all @blockid references transitively expanded inline.\n"
  "  Recursively expands references to show complete context.\n"
  "  Example: cmpr --expand-block '#root'\n"
  "\n"
  "--files-blocks\n"
  "  Print structured list of all files and their blocks.\n"
  "  Shows file names and block IDs/indices within each file.\n"
  "  Useful for understanding project structure.\n"
  "\n"
  "--print-all\n"
  "  Print all blocks in the project sequentially.\n"
  "  Outputs complete content (NL + PL) for every block.\n"
  "\n"
  "--count-blocks\n"
  "  Print total number of blocks in the project.\n"
  ;

u8 help_editing_data[] =
  "Block Editing Commands\n"
  "======================\n"
  "\n"
  "--after <id>\n"
  "  Insert new block after the specified block ID.\n"
  "  Reads new block content (NL + PL) from stdin.\n"
  "  New block is inserted in the same file.\n"
  "  Example: cat newblock.txt | cmpr --after '#INBOX'\n"
  "\n"
  "--replace <id>\n"
  "  Replace entire block (both NL and PL parts) with content from stdin.\n"
  "  Completely overwrites existing block.\n"
  "  Example: cat updated.txt | cmpr --replace '#blockid'\n"
  "\n"
  "--replace-comment <id>\n"
  "  Replace only the NL (comment) part, keeping PL unchanged.\n"
  "  Use this to update documentation without touching code.\n"
  "  Example: cat new_comment.txt | cmpr --replace-comment '#blockid'\n"
  "\n"
  "--replace-code <id>\n"
  "  Replace only the PL (code) part, keeping NL unchanged.\n"
  "  Less preferred than --rewritepl which generates from NL.\n"
  "  Example: cat new_code.c | cmpr --replace-code '#blockid'\n"
  "\n"
  "Standard Workflow:\n"
  "  1. Edit NL using --replace-comment\n"
  "  2. Regenerate PL using --rewritepl\n"
  "  3. Verify with --print-code\n"
  "  4. Test changes with dist/cmpr\n"
  "  5. Install when satisfied: sudo make install\n"
  "\n"
  "Note: Always prefer editing NL and regenerating PL over directly editing PL.\n"
  "      Mark blocks \"Manually maintained.\" only when necessary.\n"
  ;

u8 help_search_data[] =
  "Search and Navigation Commands\n"
  "==============================\n"
  "\n"
  "--grep <pattern>\n"
  "  Search all blocks using POSIX Extended Regular Expression.\n"
  "  Searches both NL (comment) and PL (code) parts.\n"
  "  Returns space-separated list of matching block IDs.\n"
  "  Outputs \"#id\" for NL matches, \"#id:code\" for PL-only matches.\n"
  "  \n"
  "  Pattern syntax: POSIX ERE (not JavaScript regex)\n"
  "  - Use [0-9] instead of \\d\n"
  "  - Use [a-zA-Z0-9_] instead of \\w\n"
  "  - Use [[:space:]] instead of \\s\n"
  "  \n"
  "  Example: cmpr --grep 'handle.*help'\n"
  "  Example: cmpr --grep '#[a-z_]+'\n"
  "\n"
  "--content-index <search>\n"
  "  Search for literal string (not regex) across all blocks.\n"
  "  Returns space-separated list of one-based indices.\n"
  "  Example: cmpr --content-index 'event_system'\n"
  "\n"
  "--files-blocks\n"
  "  Print structured list of all files and blocks.\n"
  "  Each line shows either \"file: filename\" or \"Block N: #id\".\n"
  "  Useful for understanding project structure.\n"
  "  \n"
  "  Filter to specific file:\n"
  "  cmpr --files-blocks | grep -A 1000 'file: spanio.c' | \\\n"
  "    grep -B 1000 -m 1 '^file:' | head -n -1\n"
  "\n"
  "Navigation Pattern:\n"
  "  1. Start at root: cmpr --print-comment '#root'\n"
  "  2. Follow references to hubs (2-3 hops to reach any block)\n"
  "  3. Use --grep only when navigation doesn't work\n"
  ;

u8 help_nl2pl_data[] =
  "Natural Language to Code Generation\n"
  "===================================\n"
  "\n"
  "--rewritepl <id>\n"
  "  Regenerate PL (code) from NL (comment) using LLM.\n"
  "  Sends NL part to configured LLM API.\n"
  "  Replaces PL part with generated code.\n"
  "  This is the preferred way to update code after changing NL.\n"
  "  \n"
  "  Example Workflow:\n"
  "  1. Edit NL: cat new_nl.txt | cmpr --replace-comment '#blockid'\n"
  "  2. Generate code: cmpr --rewritepl '#blockid'\n"
  "  3. Verify: cmpr --print-code '#blockid'\n"
  "  4. build or test or whatever.\n"
  "  \n"
  "  Example: cmpr --rewritepl '#handle_help_topic'\n"
  "\n"
  "--prompt <id>\n"
  "  Print the prompt that would be sent to the LLM for nl2pl conversion.\n"
  "  Does NOT call the LLM - just shows what prompt would be used.\n"
  "  Useful for debugging and understanding LLM context.\n"
  "  Example: cmpr --prompt '#blockid'\n"
  "  See also --expand.\n"
  "\n"
  "Configuration:\n"
  "  LLM settings are in .cmpr/conf:\n"
  "  - llm_command: Command to call LLM API\n"
  "  - llm_model: Model name to use\n"
  "\n"
  "NL Precision Principle:\n"
  "  The nl2pl system generates correct code only when NL is unambiguous.\n"
  "  Be explicit about:\n"
  "  - Exact algorithms\n"
  "  - Data structures  \n"
  "  - Edge cases\n"
  "  - What NOT to do\n"
  "  \n"
  "  If generated PL is wrong, fix the NL, not the PL.\n"
  "\n"
  "Manually Maintained Blocks:\n"
  "  Add \"Manually maintained.\" as last line of NL comment.\n"
  "  Only use when you MUST write PL directly.\n"
  "  Avoid when possible - prefer letting the system generate code.\n"
  "*/\n"
  ;

u8 help_events_data[] =
  "Event System (Temporal Reasoning)\n"
  "==================================\n"
  "\n"
  "The event system provides temporal reasoning through tracking events\n"
  "in transient memory (T).\n"
  "\n"
  "Core Concepts:\n"
  "  T - Transient memory (current event state)\n"
  "  E - Events (strings with associated strength values)\n"
  "  S - Strength (binary log odds, 0-255 bits of support)\n"
  "\n"
  "Commands:\n"
  "\n"
  "--T0\n"
  "  Reset T to empty state.\n"
  "  Use at start of new work session to clear transient context.\n"
  "  Example: cmpr --T0\n"
  "\n"
  "--event <string> --strength <value>\n"
  "  Add event to T with specified strength (0-255).\n"
  "  Events are deduplicated - adding duplicate updates strength.\n"
  "  Currently only strength 255 is well-supported.\n"
  "  Example: cmpr --event \"The block id is: #root\" --strength 255\n"
  "\n"
  "--T\n"
  "  Print current T state as SN (strength-notation) lines.\n"
  "  Format: \"event_string\" strength.\n"
  "  Example: cmpr --T\n"
  "\n"
  "--memorize\n"
  "  Save current T to timestamped snapshot in .cmpr/events/\n"
  "  Creates permanent record of current transient state.\n"
  "  Example: cmpr --memorize\n"
  "\n"
  "--recall\n"
  "  Use current T as query to search memorized snapshots.\n"
  "  Finds most recent snapshot containing any query event.\n"
  "  Loads all events from that snapshot into T (associative memory).\n"
  "  T must be non-empty before calling --recall.\n"
  "  Example:\n"
  "    cmpr --T0\n"
  "    cmpr --event \"The block id is: #foo\" --strength 255\n"
  "    cmpr --recall\n"
  "\n"
  "--snapshots\n"
  "  List all event snapshots with timestamps and previews.\n"
  "\n"
  "--snapshot-view <timestamp>\n"
  "  View complete contents of specific snapshot.\n"
  "  Timestamp format: YYYYMMDD-HHMMSS-nanos (from --snapshots)\n"
  "\n"
  "Workflow Pattern:\n"
  "  1. Clear T: cmpr --T0\n"
  "  2. Set context: cmpr --event \"The block id is: #foo\" --strength 255\n"
  "  3. Add facts: cmpr --event \"Block is reachable\" --strength 255\n"
  "  4. Save snapshot: cmpr --memorize\n"
  "\n"
  "T is TRANSIENT - meant to be cleared between work sessions.\n"
  "Snapshots provide HISTORICAL queries via --recall.\n"
  ;

u8 help_agents_data[] =
  "Agent System (Automated Maintenance)\n"
  "====================================\n"
  "\n"
  "Agents are executable blocks that verify and maintain wants (desired states).\n"
  "\n"
  "COMMUNICATION CONTRACT:\n"
  "\n"
  "ALL agent communication is via T (transient memory):\n"
  "  - Agents use `cmpr --event \"...\" --strength N` for ALL results\n"
  "  - NO stdout/stderr for normal operation\n"
  "  - Callers read results via `cmpr --T`\n"
  "\n"
  "Required event patterns:\n"
  "  \"Agent: <name>\" 255.\n"
  "  \"Mode: CHECK|FIX\" 255.\n"
  "  \"Status: <result>\" 255.\n"
  "  \"<domain-specific facts>\" N.\n"
  "\n"
  "Architecture:\n"
  "  Agent = Predicate (Want) + Step Function (CHECK/FIX modes)\n"
  "  \n"
  "  Four decision states:\n"
  "  1. Tracked - Want is recorded but not verified\n"
  "  2. Checked - Can determine if want is satisfied\n"
  "  3. Assisted - Can offer help with fixing\n"
  "  4. Owned - Automatically maintains the want\n"
  "\n"
  "Commands:\n"
  "\n"
  "--agents\n"
  "  List all registered agents in the project.\n"
  "  Finds blocks matching #agent_* and #cmpra_* patterns.\n"
  "\n"
  "--agent-run <agent_name> <mode>\n"
  "  Execute an agent in CHECK or FIX mode.\n"
  "  Clears T, runs agent, results appear in T.\n"
  "\n"
  "Agent Naming (new style):\n"
  "  #cmpra_<name>           - Agent hub (want + references)\n"
  "  #cmpra_<name>_check     - CHECK mode implementation\n"
  "  #cmpra_<name>_fix       - FIX mode implementation\n"
  "\n"
  "Running Agents:\n"
  "  cmpr --T0                                    # Clear T\n"
  "  cmpr --print-code '#cmpra_foo_check' | bash  # Run\n"
  "  cmpr --T                                     # Read results\n"
  "\n"
  "See: cmpr --help agent-qa (for QA process)\n"
  ;

u8 help_reports_data[] =
  "HTML Reports and Dashboards\n"
  "===========================\n"
  "\n"
  "Commands that generate HTML reports for system visibility.\n"
  "\n"
  "--wants-dashboard\n"
  "  Generate All Wants Dashboard HTML report.\n"
  "  Checks staleness and regenerates if needed (daily).\n"
  "  Creates public_html/wants_dashboard.html\n"
  "  Shows all wants grouped by decision state.\n"
  "  Requires pandoc for HTML conversion.\n"
  "  Example: cmpr --wants-dashboard\n"
  "\n"
  "--event-report\n"
  "  Generate Event System Activity Report HTML.\n"
  "  Checks staleness and regenerates if needed (daily).\n"
  "  Creates public_html/event_activity.html\n"
  "  Shows agent runs, work sessions, and metrics over time.\n"
  "  Requires pandoc for HTML conversion.\n"
  "  Example: cmpr --event-report\n"
  "\n"
  "--export-docs\n"
  "  Generate markdown reports in docs/ directory for GitHub.\n"
  "  Creates:\n"
  "    - docs/wants_dashboard.md\n"
  "    - docs/event_activity.md\n"
  "    - docs/README.md\n"
  "  Always regenerates (no staleness check).\n"
  "  Suitable for committing to version control.\n"
  "  Example: cmpr --export-docs\n"
  "\n"
  "Visualization Generators (execute via --print-code):\n"
  "  #generate_timeline_html      - Event timeline scatter plot\n"
  "  #generate_metric_plot        - Metric tracking over time\n"
  "  #generate_snapshot_stats     - Snapshot statistics\n"
  "  #generate_visualization_index - Navigation page\n"
  "\n"
  "All HTML visualizations are self-contained.\n"
  "Reports contain only metadata, no sensitive data.\n"
  "\n"
  "Note: Current visualizations use Chart.js, but we plan to remove\n"
  "this dependency in favor of a simpler approach.\n"
  ;

u8 help_wants_data[] =
  "Want Tracking and Decision States\n"
  "==================================\n"
  "\n"
  "Want = statement of desired state, dual to an agent.\n"
  "\n"
  "Commands:\n"
  "\n"
  "--wants\n"
  "  Find and print all want statements in the project.\n"
  "  Searches all files for SN lines starting with \"We want \".\n"
  "  Scans source files, .cmpr/T, and .cmpr/events/*\n"
  "  Example: cmpr --wants\n"
  "\n"
  "--agents-wants\n"
  "  Show relationship between wants and agents.\n"
  "  Displays decision state for each want:\n"
  "    - TRACKED: Want recorded, no agent\n"
  "    - CHECKED: Has CHECK implementation\n"
  "    - ASSISTED: Has CHECK and FIX implementations\n"
  "    - OWNED: Automatic maintenance (future)\n"
  "  \n"
  "  Output grouped by decision state showing:\n"
  "    - Want text\n"
  "    - Block ID containing want\n"
  "    - Agent ID (if any)\n"
  "    - Implementation blocks\n"
  "  \n"
  "  Example: cmpr --agents-wants\n"
  "\n"
  "Want Format (SN notation):\n"
  "  \"We want <description of desired state>\" <strength>.\n"
  "\n"
  "Example want statements:\n"
  "  \"We want all blocks reachable from #root in ≤2 hops\" 255.\n"
  "  \"We want the build to complete without warnings\" 255.\n"
  "\n"
  "Decision State Progression:\n"
  "  tracked → checked → assisted → owned\n"
  "\n"
  "Each state adds capability:\n"
  "  - Checked: Can verify if satisfied\n"
  "  - Assisted: Can help fix violations\n"
  "  - Owned: Automatically maintains\n"
  "\n"
  "Wants establish event spaces (desired state, complement).\n"
  "Agents verify and maintain wants through CHECK and FIX modes.\n"
  "*/\n"
  ;

u8 help_agent_qa_data[] =
  "Agent QA (Manual Quality Assurance)\n"
  "====================================\n"
  "\n"
  "Pipe this help text to an assistant: cmpr --help agent-qa | claude\n"
  "\n"
  "---\n"
  "\n"
  "ASSISTANT INSTRUCTIONS:\n"
  "\n"
  "You are performing manual QA on an agent.\n"
  "\n"
  "NAMING CONVENTIONS:\n"
  "\n"
  "New style (#cmpra_ namespace):\n"
  "  #cmpra_<name>         - Agent hub (want + references, NL only)\n"
  "  #cmpra_<name>_check   - CHECK implementation\n"
  "  #cmpra_<name>_fix     - FIX implementation (optional)\n"
  "\n"
  "Old style:\n"
  "  #agent_<name>         - Agent definition\n"
  "  #<name>_agent_check   - CHECK implementation\n"
  "  #<name>_agent_fix     - FIX implementation\n"
  "\n"
  "Both styles are valid.\n"
  "\n"
  "COMMUNICATION CONTRACT:\n"
  "\n"
  "ALL agent communication is via T (transient memory):\n"
  "  - Agents use `cmpr --event \"...\" --strength N` for ALL results\n"
  "  - NO stdout/stderr for normal operation\n"
  "  - Callers read results via `cmpr --T`\n"
  "\n"
  "Required event patterns:\n"
  "  \"Agent: <name>\" 255.\n"
  "  \"Mode: CHECK|FIX\" 255.\n"
  "  \"Status: <result>\" 255.\n"
  "\n"
  "STEP 1: Check if agent exists\n"
  "  Run: cmpr --agents | grep <agent_name>\n"
  "  \n"
  "  If no match: Agent does not exist. Stop.\n"
  "  If match: Continue.\n"
  "\n"
  "STEP 2: Find agent blocks\n"
  "  Run: cmpr --files-blocks | grep -i <agent_name>\n"
  "  \n"
  "  Look for hub and impl blocks in either naming style.\n"
  "\n"
  "STEP 3: Read agent hub/definition\n"
  "  Run: cmpr --print-comment '#cmpra_<name>' or '#agent_<name>'\n"
  "  \n"
  "  Check for:\n"
  "    - Want statement\n"
  "    - References to CHECK/FIX implementations\n"
  "\n"
  "STEP 4: Verify CHECK implementation\n"
  "  Clear T and run:\n"
  "    cmpr --T0\n"
  "    cmpr --print-code '#<check_block>' | bash\n"
  "    cmpr --T\n"
  "  \n"
  "  Verify output contains required event patterns.\n"
  "\n"
  "STEP 5: Report\n"
  "  - Hub: exists/missing\n"
  "  - CHECK: exists/missing (and uses T communication)\n"
  "  - FIX: exists/missing\n"
  "  - Run command\n"
  "\n"
  "---\n"
  "\n"
  ;

span get_help_text(char *topic) {
    span s;
    s.buf = 0;
    s.end = 0;
    
    if (!topic) {
        s.buf = help_summary_data;
        s.end = s.buf + sizeof(help_summary_data) - 1;
    } else if (strcmp(topic, "topics") == 0) {
        s.buf = help_topics_data;
        s.end = s.buf + sizeof(help_topics_data) - 1;
    } else if (strcmp(topic, "basic") == 0) {
        s.buf = help_basic_data;
        s.end = s.buf + sizeof(help_basic_data) - 1;
    } else if (strcmp(topic, "blocks") == 0) {
        s.buf = help_blocks_data;
        s.end = s.buf + sizeof(help_blocks_data) - 1;
    } else if (strcmp(topic, "editing") == 0) {
        s.buf = help_editing_data;
        s.end = s.buf + sizeof(help_editing_data) - 1;
    } else if (strcmp(topic, "search") == 0) {
        s.buf = help_search_data;
        s.end = s.buf + sizeof(help_search_data) - 1;
    } else if (strcmp(topic, "nl2pl") == 0) {
        s.buf = help_nl2pl_data;
        s.end = s.buf + sizeof(help_nl2pl_data) - 1;
    } else if (strcmp(topic, "events") == 0) {
        s.buf = help_events_data;
        s.end = s.buf + sizeof(help_events_data) - 1;
    } else if (strcmp(topic, "agents") == 0) {
        s.buf = help_agents_data;
        s.end = s.buf + sizeof(help_agents_data) - 1;
    } else if (strcmp(topic, "reports") == 0) {
        s.buf = help_reports_data;
        s.end = s.buf + sizeof(help_reports_data) - 1;
    } else if (strcmp(topic, "wants") == 0) {
        s.buf = help_wants_data;
        s.end = s.buf + sizeof(help_wants_data) - 1;
    } else if (strcmp(topic, "agent-qa") == 0) {
        s.buf = help_agent_qa_data;
        s.end = s.buf + sizeof(help_agent_qa_data) - 1;
    }
    
    return s;
}
